# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
  - name: pool
    displayName: Agent Pool
    type: string
    default: 'Default'
    values:
      - 'Default'
  - name: Actions
    displayName: 'Actions'
    type: string
    default: 'Create'
    values:
      - 'Create'
      - 'Destroy'

trigger: none

stages:
  - stage: Init
    jobs:
      - job: Init
        pool: ${{ parameters.pool }}
        steps:
          - script: terraform init
            displayName: 'Terraform Init'
          - script: terraform validate
            displayName: 'Terraform Validate'
  - stage: Create
    condition: and(succeeded(), eq(parameters['Actions'], 'Create'))
    jobs:
      - job: Plan
        pool: ${{ parameters.pool }}
        steps:
          - script: terraform plan
            displayName: 'Terraform Plan'
      - deployment: Create
        pool: ${{ parameters.pool }}
        environment: 'Dev'
        strategy:
          runOnce:
            deploy:
              steps:
                - script: terraform apply -auto-approve
                  displayName: 'Terraform Apply'
      # - job: Apply
      #   condition: succeeded()
      #   pool: ${{ parameters.pool }}
      #   steps:
      #     - script: terraform apply -auto-approve
      #       displayName: 'Terraform Apply'
      
  - stage: Destroy
    condition: and(succeeded(), eq(parameters['Actions'], 'Destroy'))
    jobs:
      - job: Destroy
        pool: ${{ parameters.pool }}
        steps:
          - script: terraform destroy -auto-approve
            displayName: 'Terraform Destroy'
